### ISSUE TITLE
Processing geoJSON power plant list

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcam-driver#2]
We want to be able to take a list of power plant locations, stored in a geoJSON `FeatureCollection`, and convert them into a gridded representation of water usage.  We get the water usage for each plant by multiplying the plant's capacity by an average water usage determined by the plant's type.

The gridded output will be sparse (i.e., most grid cells zero), so it will be useful to have the output in a sparse representation.  I'm thinking something like
```
 { "type": "FeatureCollection",
    "features": [
         { "type": "Feature",
        "geometry": {"type" : "Point", "coordinates": [69.113400, 34.563800]},
        "properties": {"water-withdrawal":  0.4, "units": "km^3"}
        },
         { "type": "Feature",
        "geometry": {"type" : "Point", "coordinates": [19.434000, 40.487400]},
        "properties": {"water-withdrawal":  0.25, "units": "km^3"}
        },
    ...
   ]
}
```
So, the function that does this processing will need to take a list of conversion factors and a dictionary of water usage factors for each plant type, and it will return a geoJSON structure (i.e., a python structure that could exported using the `json.dump()` function) like the one above.

Since we will be using this output in code that may not be entirely capable of processing JSON, we will want to have another function that converts this to a list of tuples:
```
[(lon, lat, val),
 (lon, lat, val),
 ...
]
```
We can put these new functions in a module called "geotools" under the "gcam" package.

We will also need a function to write a list of tuples like the one above to a file as a three-column csv.  We can put that one in the `gcam.util` module.

**Comment by ssmithClimate** [comment]
This sort of capability, and dataset, will also be central to the historical (and even future) emissions gridding routines that we will develop for CEDS.

________________________________

**Comment by rplzzz** [comment]
Yes, eventually we will want to generalize.  For right now, I'm just going for something that will work for the specific project we're working on, but hopefully it will be a useful building block.

By the way, is everyone who has access to this repository getting notifications about issues here?  I don't want to clutter everyone's inbox with stuff that may not be relevant to them.
